import type { Metadata } from "next"

import Container from "@/components/Container"

import "./globals.css"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  )
}
