import type { ServerBuild } from "react-router";

import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-expect-error - the server build file is generated by `react-router build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build: build as ServerBuild,
});
